<script lang="ts">
  import EngCV from '$lib/EngCV.svelte';
  import type { PageData } from './$types';

  interface Props {
    data: PageData;
  }

  let { data }: Props = $props();
  // Use the pdfLink already generated by coalesceVersion
  const pdfLink = data.pdfLink || '/morgan-williams.pdf';
</script>

<EngCV {...data} version={data.slug} pdfLink={pdfLink} />