<script lang="ts">
    import CV from "$lib/CV.svelte";
    import type { PageData } from "./$types";

    export let data: PageData;

    // Use the pdfLink already generated by coalesceVersion
    const pdfLink =
        data.slug === "main"
            ? "/morgan-williams.pdf"
            : `/morgan-williams.${data.slug}.pdf`;
</script>

<CV {...data} {pdfLink} />
